name: CowDetonator
version: '1.0-SNAPSHOT'
main: org.mbf.cowdetonator.CowDetonator
api-version: '1.20'
commands:
  cowbomb:
    description: Plant a cow
    usage: /cowbomb [sneaky]
    permission: cowbomb.plantcow

